explodio/accounts/urls.py
from django.conf.urls import patterns, url

from explodio.accounts import views


urlpatterns = patterns('',
    # The login page.
    url(r'^login/$',
        views.LoginView.as_view(),
        name='login'),

    # The logout page.
    url(r'^logout/$',
        views.LogoutView.as_view(),
        name='logout'),

)

explodio/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('explodio.main.urls', namespace='main')),
    url(r'^paste/', include('explodio.paste.urls', namespace='paste')),
    url(r'^xfit/', include('explodio.xfit.urls', namespace='xfit')),
    url(r'^accounts/', include('explodio.accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
)

explodio/xfit/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from explodio.xfit import views


urlpatterns = patterns('',
    # The WOD page.
    url(r'^$',
        login_required(views.IndexView.as_view()),
        name='index'),

    # The WOD page stats.
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$',
        login_required(views.IndexView.as_view()),
        name='index'),

    # The comparison page.

    # The gym page.

    # The workout page.

    # The exercise page.
    url(r'^exercise/$',
        views.ExerciseView.as_view(), # Redirects to /exercise/all/
        name='exercise'),
    url(r'^exercise/(?P<slug>[A-Za-z-0-9-_]+)/$',
        views.ExerciseView.as_view(),
        name='exercise'),

    # The stats page.

    # The graphs page.

    # The gamification page.

    # The high-score page.
)

explodio/xfit/views.py
from datetime import date, timedelta

from django import http
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from explodio.common import iterator
from explodio.xfit import forms
from explodio.xfit import models


class XFitView(TemplateView):
    """
    XFitView helper functions
    """

    def get_gyms(self, user=None):
        """
        Get a list of Gyms for a user.
        :param user: User to get gyms for, pulled from request by default
        :return: Gym QuerySet
        """
        if user is None and self.request.user.is_authenticated():
            user = self.request.user
        q = models.Gym.objects.active()
        if user:
            q = q.subscribed_by(user)
        return q

    def get_wods(self, day=None):
        """
        Gets a list of WorkoutOfTheDay
        :param day: Specific day to get WODs for, defaults to today
        :return: QuerySet of WorkoutOfTheDay
        """
        if day is None:
            day = date.today()
        q = models.WorkoutOfTheDay.objects.for_day(day).active()
        return q

    def get_user_wods(self, user=None, day=None):
        """
        Gets UserWODs for a User for a day
        :param user: User to get gyms for, pulled from request by default
        :param day: Specific day to get WODs for, defaults to today
        :return: QuerySet of UserWOD
        """
        if user is None and self.request.user.is_authenticated():
            user = self.request.user
        if day is None:
            day = date.today()
        q = models.UserWOD.objects \
            .for_user(user) \
            .for_day(day) \
            .select_related('wod')
        return q

    def get_wod_pairs(self, user=None, day=None):
        """
        Returns WODs paired to UserWODs
        :param user: User to get gyms for, pulled from request by default
        :param day: Specific day to get WODs for, defaults to today
        :return: list of (WorkoutOfTheDay, UserWOD or None)
        """
        wods = self.get_wods(day)
        user_wods = self.get_user_wods(user, day)
        pairs = iterator.pair_left(wods, user_wods,
            searcher=lambda wod, uw: uw.wod.id == wod.id)
        return pairs

    def get_wod_forms(self, data, user=None, day=None):
        """
        Build UserWODForms using the given POST data, for a User and day
        :param data: POST data to apply to forms
        :param user: User to get gyms for, pulled from request by default
        :param day: Specific day to get WODs for, defaults to today
        :return: list of UserWODForm
        """
        if user is None and self.request.user.is_authenticated():
            user = self.request.user
        wod_pairs = self.get_wod_pairs(user=user, day=day)

        wod_forms = []

        for index, pair in enumerate(wod_pairs):
            wod, user_wod = pair
            wod_form = forms.UserWODForm(user, wod, user_wod, index, data)
            wod_forms.append(wod_form)

        return wod_forms

    def add_day_information(self, context, day=None):
        """
        Add context variables about today, tomorrow, and yesterday.
        :param context: Context dict to update
        :param day: Optional day to base tomrrow and yesterday on
        """
        if day is None:
            day = date.today()
        context['day'] = day
        context['yesterday'] = day - timedelta(days=1)
        context['tomorrow'] = day + timedelta(days=1)


class IndexView(XFitView):
    """
    The index page.
    """

    template_name = 'xfit/index.html'

    def get_day(self, **kwargs):
        """
        Extra a date from kwargs 'year', 'month', and 'day'
        :param kwargs: Request **kwargs
        :return: Date, today by default
        """
        year = kwargs.get('year')
        month = kwargs.get('month')
        day = kwargs.get('day')
        result = None
        if year and month and day:
            try:
                result = date(int(year, 10), int(month, 10), int(day, 10))
            except: # Invalid input
                pass
        if not result:
            result = date.today()
        return result

    def get_context_data(self, **kwargs):
        """
        Supply context to index.html
        - gyms (QuerySet of Gyms)
        - wod_forms (list of UserWODForm)
        - extra_gyms (gyms that don't have WODs for the given day)
        - day (day being displayed)
        - yesterday (previous day)
        - tomorrow (next day)
        :param kwargs: Request **kwargs
        :return: Context dict
        """
        gyms = self.get_gyms()
        day = self.get_day(**kwargs)
        wod_forms = self.get_wod_forms(self.request.POST or None, day=day)
        gyms_with_wods = set((wod_form.wod.gym for wod_form in wod_forms))
        extra_gyms = set(gyms) - set(gyms_with_wods)

        ctx = {
            'gyms': gyms,
            'wod_forms': wod_forms,
            'extra_gyms': extra_gyms
        }
        self.add_day_information(ctx, day=day)

        return ctx

    def post(self, request, *args, **kwargs):
        """
        Handle POST method.
        :param request: View request
        :param args: View *args
        :param kwargs: View **kwargs
        :return: HttpResponse
        """
        action = request.POST.get('action')

        if action == 'update-wods':
            return self.post_update_wods(request, *args, **kwargs)

        # Unknown action
        return http.HttpResponseBadRequest()

    def post_update_wods(self, request, *args, **kwargs):
        """
        POST UserWODForm data.
        :param request: View request
        :param args: View *args
        :param kwargs: View **kwargs
        :return: HttpResponse
        """
        ctx = self.get_context_data(**kwargs)
        day = ctx['day']

        wod_forms = ctx['wod_forms']

        valid = all((wod_form.is_valid() for wod_form in wod_forms))

        if valid:
            for wod_form in wod_forms:
                wod_form.save()
            messages.info(request, 'Workouts saved')
        else:
            messages.error(request, 'Form error')
            return self.render_to_response(ctx)

        return http.HttpResponseRedirect(reverse(
            'xfit:index',
            args=(),
            kwargs={
                'year': day.year,
                'month': day.month,
                'day': day.day
            }
        ))


class ExerciseView(XFitView):

    template_name = 'xfit/exercise.html'

    def get_context_data(self, **kwargs):
        """
        Get the context for this view.
        - slug (request exercise slug)
        - exercise (exercise object specified by the slug url param)
        - history: (for logged in users, a sequence of WODExercises 
            for the exercise)
        - day (today)
        - yesterday (previous day)
        - tomorrow (next day)
        :param kwargs: Request **kwargs
        :return: Context dict
        """
        slug = kwargs.get('slug')

        day = date.today()
        yesterday = day - timedelta(days=1)
        tomorrow = day + timedelta(days=1)

        if slug != 'all':
            exercise = get_object_or_404(models.Exercise, slug=slug)
        else:
            exercise = None

        if self.request.user.is_authenticated():
            history = models.WODExercise.objects \
                .for_user(self.request.user) \
                .select_related('user_wod__wod')
            if slug != 'all':
                history = history.for_exercise(exercise)
            else:
                history = history.order_by('goal__exercise__title')

        else:
            history = None

        ctx = {
            'slug': slug,
            'exercise': exercise,
            'history': history,
        }
        self.add_day_information(ctx)

        return ctx

    def get(self, request, *args, **kwargs):
        """
        Redirect /exercise/ requests to /exercise/all/, otherwise
        show the intended /exercise/whatever/ page.
        """

        slug = kwargs.get('slug')

        if not slug:
            return http.HttpResponseRedirect(reverse('xfit:exercise', kwargs={'slug': 'all'}))
        else:
            ctx = self.get_context_data(**kwargs)
            return self.render_to_response(ctx)

explodio/xfit/templates/xfit/base.html
{% extends "base.html" %}

{% block header %}
  <ul id="day-nav">
  	{% if day %}
    <li id="day-prev"><a href="{% url 'xfit:index' year=yesterday.year month=yesterday.month day=yesterday.day %}">{{ yesterday }}</a></li>
    <li id="day-now"><a href="{% url 'xfit:index' year=day.year month=day.month day=day.day %}">{{ day }}</a></li>
    <li id="day-next"><a href="{% url 'xfit:index' year=tomorrow.year month=tomorrow.month day=tomorrow.day %}">{{ tomorrow }}</a></li>
    {% endif %}
    <li id="logout"><a href="{% url 'accounts:logout' %}">Logout</a></li>
  </ul>
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/xfit.css" />
{% endblock css %}

explodio/xfit/templates/xfit/exercise.html
{% extends "xfit/base.html" %}

{% block content %}

<ul id="formlist">
  <li class="wod">
    {% ifequal slug 'all' %}
    <h3 class="wod-gym">All Exercises</h3>
    <h4 class="wod-title">Complete History</h4>
    {% else %}
    <h3 class="wod-gym">
      <a href="{{ exercise.get_absoute_url }}">{{ exercise }}</a>
    </h3>
    <h4 class="wod-title">Exercise History</h4>
    {% endifequal %}
    <ul class="exercises">
      {% for past in history %}
      <li class="exercise">
        {% with past.user_wod.wod.day as day %}
        <a href="{% url 'xfit:index' year=day.year month=day.month day=day.day %}">{{ past }}</a>
        {% endwith %}
      </li>
      {% empty %}
        {% if request.user.is_authenticated %}
      <li class="exercise">You have no history here&hellip; C'mon!</li>
        {% else %}
      <li class="exercise">You aren't logged in! Log in and get moving.</li>
        {% endif %}
      {% endfor %}
    <ul>
  </li>
</ul>

{% endblock content %}

explodio/xfit/templates/xfit/index.html
{% extends "xfit/base.html" %}

{% block content %}

  <form method="post" action="">
    <ul id="formlist">
      <li class="submit-container"></li>
      {% for wod_form in wod_forms %}
        <li class="wod">
          <h3 class="wod-gym">{{ wod_form.wod.gym }}</h3>
          <h4 class="wod-title">{{ wod_form.wod.workout }}</h4>

          {% if wod_form.wod.workout.high_round_divisor > 1 %}
          <h4 class="wod-title">Repeat {{ wod_form.wod.workout.high_round_divisor }} times</h4>
          {% endif %}

          {% if wod_form.wod.workout.exercises.exists %}

          {% if wod_form.score_form %}
          <div class="wod-score wod-field">{{ wod_form.score_form.as_p }}</div>
          {% endif %}

          <ul class="wod-exercises">
            {% for wod_exercise_form in wod_form.wod_exercise_forms %}
              <li class="wod-exercise">
                <div class="wod-goal">
                  <a href="{{ wod_exercise_form.goal.exercise.get_absolute_url }}">{{ wod_exercise_form.goal }}</a>
                </div>
                {% if wod_exercise_form.non_field_errors %}
                  <div class="wod-errors">{{ wod_exercise_form.non_field_errors }}</div>
                {% endif %}
                {% if wod_exercise_form.fields.effort %}
                  <div class="wod-field">
                    {{ wod_exercise_form.effort.errors }}
                    <label>{{ wod_exercise_form.goal.effort_unit.plural|capfirst }}:</label>
                    {{ wod_exercise_form.effort }}
                  </div>
                {% endif %}
                {% if wod_exercise_form.fields.reps %}
                  <div class="wod-field">
                    {{ wod_exercise_form.reps.errors }}
                    <label>{{ wod_exercise_form.goal.reps_unit.plural|capfirst }}:</label>
                    {{ wod_exercise_form.reps }}
                  </div>
                {% endif %}
                <div class="wod-field">
                  {{ wod_exercise_form.notes.errors }}
                  <label>Notes:</label>
                  <div class="notes">{{ wod_exercise_form.notes }}</div>
                </div>
              </li>
            {% endfor %}
            <button class="submit-wod" type="submit" name="action" value="update-wods">Save</button>
          </ul>

          {% else %}
            <div class="no-exercise">There are no exercises for this routine.</div>
          {% endif %}

        </li>
      {% endfor %}

      {% for gym in extra_gyms %}
      <li class="wod">
        <h3 class="wod-title">{{ gym }}</h3>
        <div class="no-exercise">Either nothing is planned today, or someone is busy lifting hundred pound rocks.</div>
      </li>
      {% endfor %}
    </ul>
    {% csrf_token %}
  </form>
{% endblock content %}